# Generated by Django 4.2.3 on 2023-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snum', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('pno', models.IntegerField()),
                ('pnum', models.CharField(max_length=50)),
                ('pr', models.IntegerField()),
                ('pd', models.TextField(max_length=100)),
                ('img', models.ImageField(upload_to='products')),
            ],
        ),
    ]
