# Generated by Django 4.2.3 on 2023-07-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='img',
            field=models.ImageField(upload_to='products/img'),
        ),
    ]
