# Generated by Django 4.2.3 on 2023-07-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_sell_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='pd',
            field=models.TextField(),
        ),
    ]
