# Generated by Django 4.2.3 on 2023-07-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_sell_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='img',
            field=models.ImageField(upload_to='media/products/img'),
        ),
    ]
