# Generated by Django 4.2.3 on 2023-07-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_sell_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='_pvt',
            field=models.CharField(default=0, max_length=11),
        ),
    ]
