# Generated by Django 4.2.3 on 2023-07-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_sell__pvt'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnam', models.CharField(max_length=30)),
                ('gm', models.EmailField(max_length=254)),
                ('ph', models.IntegerField(max_length=12)),
                ('dob', models.DateField()),
                ('_bpt', models.CharField(max_length=11)),
                ('avl', models.BooleanField(default=False)),
            ],
        ),
    ]
