# Generated by Django 4.2.3 on 2023-07-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='ph',
            field=models.IntegerField(),
        ),
    ]
