# Generated by Django 4.2.3 on 2023-07-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_buy_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='dob',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
